### ISSUE TITLE
i do not see the drafts in the CMS

### ISSUE THREAD

**Issue by mi32dogs** [heyday/silverstripe-versioneddataobjects#18]
Hi,
First of all thank you for this extension.
I installed it but in the CMS I get only the published records i do not see the drafts in the gridfield any idea on what i'm doing wrong?

Thanks 
Rob

**Comment by stecman** [comment]
Hi Rob, do the draft records show up when you switch the site to viewing draft (tack `?stage=Stage` on the end of the URL)? If so, this is a known issue that comes from SilverStripe's `Versioned` data extension modifying all database queries based on a global "reading mode" state by default.

Depending on the context, the solution differs:

* If you have control over the query, you can alter the behaviour of `Versioned` with dataquery parameters to always get draft and live records:

  ```php
  VersionedFoo::get()
	->setDataQueryParam(['Versioned.stage' => 'Stage']);
  ```
* If you can't modify the query, you can use [`VersionedReadingMode`](https://github.com/heyday/silverstripe-versioneddataobjects/blob/master/code/VersionedReadingMode.php) from this module to change and restore the global reading mode:
  
  ```php
  VersionedReadingMode::setStageReadingMode();
  
  // ... code that runs queries

  VersionedReadingMode::restoreOriginalReadingMode();
  ```

* If you need a model admin to manage versioned dataobjects, you can use `VersionedModelAdmin` from this module in place of `ModelAdmin`

**Comment by mi32dogs** [comment]
Thank you that worked great!, i did not know that the ?stage=Stage worked in the admin.

I used the 
VersionedFoo::getList()
  ->setDataQueryParam(['Versioned.stage' => 'Stage']);
and it works like a charm.

Thank you so much
