### ISSUE TITLE
How to use in Model Admin?

### ISSUE THREAD

**Issue by JustinTBrown** [heyday/silverstripe-versioneddataobjects#27]
I've been tinkering for a while, but it's not yet clear to me how to add this to a DataObject I'm managing through Model Admin. For example:

```php
class Event extends DataObject {
  static $db = array(
    'Title' => 'Varchar(255)',
  );

  private static $extensions = array(
      'VersionedDataObject'
  );
}
```

Which is managed via:

```php
class Event_Admin extends ModelAdmin {
  public static $managed_models = array('Event');
  public static $url_segment = 'events';
  public static $menu_title = 'Events';
}
```

How do I access the necessary form field config and add/remove the required components?

Hopefully this question makes sense.

**Comment by camspiers** [comment]
There is a VersionedModelAdmin class I believe

**Comment by stecman** [comment]
Closing this as it's now detailed in the readme.
