### ISSUE TITLE
Version 1.5 incompatible with Better Buttons 

### ISSUE THREAD

**Issue by MattyBalaam** [heyday/silverstripe-versioneddataobjects#32]
I'm not sure if this should be an issue here, but I wanted to note that while version 1.4 and below work well with https://github.com/unclecheese/silverstripe-gridfield-betterbuttons , moving to 1.5 or above removes any versioning related buttons.

**Comment by adrexia** [comment]
We've also been experiencing this.  I'm going to follow the recommendations and downgrade to better buttons 1.2.8.

**Comment by jebates** [comment]
Thanks, this is fixed in release 2.0.1 by merging the change from @adrexia.
