### ISSUE TITLE
VersionedModelAdmin not working in v2

### ISSUE THREAD

**Issue by bigSiebs** [heyday/silverstripe-versioneddataobjects#40]
Using the latest version of your module, I attempted to add data-object versioning to a model-admin page following the Slice/SliceAdmin example in the README. When I changed `extends ModelAdmin` to `extends VersionedModelAdmin` in my model-admin class, the page became inaccessible in the CMS. I rolled back the module to v1.4, and I was able to access the page again (with versioning), which makes me suspect that something in a recent release broke it.

**Comment by bigSiebs** [comment]
It appears that this was just a namespacing issue. Could you make the following update to the documentation?
```class SliceAdmin extends VersionedModelAdmin```
becomes
```class SliceAdmin extends Heyday\VersionedDataObjects\VersionedModelAdmin```

**Comment by jebates** [comment]
Hi bigSiebs, thanks for pointing that out and letting us know. We have now updated the README.md with that missing namespace. See release 2.0.5 - cheers.
