### ISSUE TITLE
Broken with SS 3.7 due to duplicate class name

### ISSUE THREAD

**Issue by dhensby** [heyday/silverstripe-versioneddataobjects#47]
silverstripe/framework:3.7 has introduced a new class named `VersionedReadingMode` which means this module does not work on 3.7

Affected version 1.x

**Comment by shane-nzer** [comment]
Namespaces were added from version 2.0.

**Comment by dhensby** [comment]
Ah, and v2.0 is SS 3 compat, I guess? thanks

**Comment by dhensby** [comment]
OK - just in case anyone stumbles across this and they want to upgrade v1 to v2 I *think* a really easy shim for painless upgrades is to add a class to your code called `VersionedDataObject` and have it `extend` `Heyday\VersionedDataObjects\VersionedDataObject` and then it seems to "just work".

@shane-garelja you may want to add that to your docs as an "upgrading guide"
