### ISSUE TITLE
Gridfield Record Editor Delete

### ISSUE THREAD

**Issue by MattyBalaam** [heyday/silverstripe-versioneddataobjects#5]
Am I right in thinking that any deleting needs to happen in the VersionedDataObjectDetailsForm? Removing objects in the gridfield seems to be leaving the objects on the _Live table.

**Comment by stecman** [comment]
This was fixed in 02b7b5e44509ab5476ab45c96836959a9c8a5e23 a short while ago. There was an issue where the module behaviour differed depending on the current reading mode.
